##### Menu
menu:
  首页: /
  归档: /archives
  关于: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets 卡片
widgets:
- github-card
- category
- tag
- tagcloud
- weixin #微信二维码模块
- weibo  #
- earth  #访客地图卡片
- rss
- links  #友情链接

  ## provide eight widgets:github-card,category,tag,rss,archive,tagcloud,links,weibo


#### RSS 
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     
apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: img/banner.jpg ## size:1920px*200px+. Banner Picture

weixinimg: img/weixinimg.jpg

### Theme Color 
theme_color:
    theme: '#2ca6cb'    ##the defaut theme color is blue

# 代码高亮主题
# available: default | night
highlight_theme: default

#### index post is expanding or not 
index:
  expand: false           ## false为摘要 true 全开
  excerpt_link: 更多...

close_aside: false  #close sidebar in post page if true
mathjax: true      #enable mathjax if true

### Creative Commons License Support, see http://creativecommons.org/ 
### you can choose: by , by-nc , by-nc-nd , by-nc-sa , by-nd , by-sa , zero
creative_commons: none

#### Author information
author:
  intro_line1:  "嗨，见文如晤，多多指教."    ## your introduction on the bottom of the page
  intro_line2:  "粗浅见解，修葺成文，盼广交同道中人."  ## the 2nd line
  weibo: 1791281385   ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  weibo_verifier: 8c6f2d1f     ## e.g. b3593ceb Your weibo-show widget verifier ,if you use weibo-show it is needed.
  tsina: 1791281385     ## e.g. 2176287895  Your weibo ID,It will be used in share button.
  douban: boyers    ## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014
  zhihu: boyers     ## e.g. jark  for http://www.zhihu.com/people/jark
  email: 724987481@qq.com     ## e.g. imjark@gmail.com
  twitter:    ## e.g. jarkwu for https://twitter.com/jarkwu
  github: huos3203    ## e.g. wuchong for https://github.com/wuchong
  facebook:   ## e.g. imjark for https://facebook.com/imjark
  linkedin: boyerswift  ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
  google_plus:    ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
  stackoverflow: 6211905 ## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
## if you set them, the corresponding  share button will show on the footer

#### Toc  启用在文章中或侧边栏中的目录功能
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
    swift文档: https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/
    objc中国: https://www.objccn.io
    NSHipster: http://nshipster.cn
    动画: https://github.com/AttackOnDobby/iOS-Core-Animation-Advanced-Techniques
    Git Pro: https://git-scm.com/book/zh
    全盘搜: http://kaopu.so/pan
    小程序官方: https://mp.weixin.qq.com
    王维: https://onevcat.com
    唐巧: http://blog.devtang.com


#### Comment
# short_name string 必须 站点注册的多说二级域名。注意：你注册了http://apitest.duoshuo.com/时，多说二级域名为**apitest**。
# threads string 必须 你需要获取的文章的thread-key，可传递多个thread_key，即文章在原站点中的id，与评论框中data-thread-key一致。用逗号分割。例如：4ff160411318693231000006,4ff160411318693231000007
duoshuo_shortname: #huo3203   ## e.g. wuchong   your duoshuo short name. 第二域名：即为shorname
# duoshuo_comments: true  
# duoshuo_asides_num: 10      # 侧边栏评论显示条目数
# duoshuo_asides_avatars: 0   # 侧边栏评论是否显示头像
# duoshuo_asides_time: 0      # 侧边栏评论是否显示时间
# duoshuo_asides_title: 0     # 侧边栏评论是否显示标题
# duoshuo_asides_admin: 1     # 侧边栏评论是否显示作者评论
# duoshuo_asides_length: 18   # 侧边栏评论截取的长度

disqus_shortname:     ## e.g. wuchong   your disqus short name.

#### Share button
jiathis:
  enable: true ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID. 
  tsina: 1791281385 ## e.g. 2176287895 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: false
  id: UA-51742113-2       ## e.g. UA-46321946-2 your google analytics ID.
  site:      ## e.g. wuchong.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_tongji:
  enable: true 
  sitecode: b4a2528a681e2f23855d15a4de0abfc2 ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code
  gitsitecode: cda1b75e08a0a3e897aa6f92112910b4
cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true


#### Custom Search
google_cse: 
  enable: false
  cx:   ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
baidu_search:     ## http://zn.baidu.com/
  enable: true
  id: SE_zzsearchcode_shhzc78w  ## e.g. "783281470518440642"  for your baidu search id
site: http://zhannei.baidu.com/cse/search #http://boyers.coding.me  ## your can change to your site instead of the default site
  
tinysou_search:     ## http://tinysou.com/
  enable: false
  id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id
